user evgeniy;

events {
    worker_connections 1024;
}

http {
    access_log logs/access.log;
    error_log logs/error.log;

    upstream main {
        server localhost:8000;
    }

    server {
        listen 81;
        server_name localhost;


        location / {
            proxy_pass http://main;
        }

        location /users/ {
            proxy_pass http://main;
        }

        location /docs {
            proxy_pass http://main/docs;
        }

        location /test {
            return 200 "nginx works";
        }

        location /token {
            access_by_lua_file src/gateway/lua/check_token.lua;

        }
    }
}